framework:
    default_locale: en
    enabled_locales: [en,es,fr]
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        enabled: true
        paths:
            #            - '%kernel.project_dir%/translations/manual'
            - '%kernel.project_dir%/translations/auto'
        #            - '%kernel.project_dir%/translations/'
